version: '3.7'

services:
  web:
    build: ./services/web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
      - TZ="Europe/Moscow"
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=example
    - TZ="Europe/Moscow"
  coap:
    build: ./services/coap
    command: python manage.py run
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5683:1222/udp"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 1337:80
    depends_on:
      - web
      - coap
  api-gateway:
    build: ./sevice/api-gateway

volumes:
  postgres_data:
  static_volume: