version: '3.7'

services:
  web:
    build: ./services/web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
      - TZ="Europe/Moscow"
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=example
    - TZ="Europe/Moscow"
  coap:
    build: ./services/coap
    command: python manage.py run
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5683:1222/udp"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 1337:80
      - 443:443
    restart: always
    volumes:
      - static_volume:/home/app/web/project/static
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
      - coap
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email moddinshell@gmail.com --agree-tos --no-eff-email -d sinbiot.ru
volumes:
  postgres_data:
  static_volume: