version: '3.7'

services:
  #  web:
  #    build: ./services/web
  #    command: gunicorn --bind 0.0.0.0:5000 manage:app
  #    volumes:
  #      - static_volume:/home/app/web/app/static
  #    expose:
  #      - "5000"
  #    env_file:
  #      - ./.env.dev
  #    depends_on:
  #      - db
  db:
    build: ./services/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
  coap:
    build: ./services/coap
    command: python manage.py run
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5683:1222/udp"
    #      env_file:
    #        - ./.env.dev
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
      - 443:443
    restart: always
#    volumes:
#      - static_volume:/home/app/web/app/static
    depends_on:
      #        - web
      - coap
      - api-gateway
  api-gateway:
    build: ./services/api-gateway
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8080:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
#    command: certonly --webroot --webroot-path=/var/www/certbot/ --email moddinshell@gmail.com --agree-tos --no-eff-email -d sinbiot.ru
#volumes:
#  postgres_data:
#  static_volume: